### ISSUE TITLE
Fix this error?

### ISSUE THREAD

**Issue by thecao365** [Haehnchen/crypto-trading-bot#12]
Can you guide me to fix this error?

```
r00t@ubuntu:~/crypto-trading-bot$ node index.js trade
undefined:41
    },
    ^

SyntaxError: Unexpected token } in JSON at position 1079
    at JSON.parse (<anonymous>)
    at Object.boot (/home/r00t/crypto-trading-bot/modules/services.js:94:23)
    at Object.<anonymous> (/home/r00t/crypto-trading-bot/index.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)

```

**Comment by Haehnchen** [comment]
sry this was a simple synax issue inside `conf.json.dist` is fixed now: https://github.com/Haehnchen/crypto-trading-bot/blob/master/conf.json.dist

**Comment by minerlab** [comment]
solved? not work form me, same error 
crypto-trading-bot$ node index.js trade

/home/psyco/crypto-trading-bot/modules/services.js:121
            throw 'Invalid conf.json file. Please check: ' + String(e)
            ^
Invalid conf.json file. Please check: SyntaxError: Unexpected token R in JSON at position 145
