### ISSUE TITLE
Installation requirements / errors

### ISSUE THREAD

**Issue by TopSecretShares** [Haehnchen/crypto-trading-bot#16]
Hi Daniel, 

It's awesome what you implemented here the tons of awesome implementations. Respect.

Can you please provide requirements for a proper installation, please? Like OS, nodejs version, Development Tools etc. I made it up and running with changes but I met heaps of errors on the way trying different OSes.

`
> tulind@0.8.13 install /home/crypto/crypto-trading-bot/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download

/home/crypto/crypto-trading-bot/node_modules/tulind/node_modules/node-pre-gyp/node_modules/tar/lib/create.js:4
const hlo = require('./high-level-opt.js')
^^^^^
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack SyntaxError: Use of const in strict mode.
node-pre-gyp ERR! stack     at Module._compile (module.js:439:25)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! stack     at Module.require (module.js:364:17)
node-pre-gyp ERR! stack     at require (module.js:380:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/crypto/crypto-trading-bot/node_modules/tulind/node_modules/node-pre-gyp/node_modules/tar/index.js:4:30)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! System Linux 3.10.0-957.el7.x86_64
node-pre-gyp ERR! command "node" "/home/crypto/crypto-trading-bot/node_modules/tulind/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/crypto/crypto-trading-bot/node_modules/tulind
node-pre-gyp ERR! node -v v0.10.30
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN engine deep-extend@0.6.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine ret@0.1.15: wanted: {"node":">=0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine atob@2.1.2: wanted: {"node":">= 4.5.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
|
> sqlite3@4.0.4 install /home/crypto/crypto-trading-bot/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download

/home/crypto/crypto-trading-bot/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar/lib/create.js:4
const hlo = require('./high-level-opt.js')
^^^^^
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack SyntaxError: Use of const in strict mode.
node-pre-gyp ERR! stack     at Module._compile (module.js:439:25)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! stack     at Module.require (module.js:364:17)
node-pre-gyp ERR! stack     at require (module.js:380:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/crypto/crypto-trading-bot/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar/index.js:4:30)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! System Linux 3.10.0-957.el7.x86_64
node-pre-gyp ERR! command "node" "/home/crypto/crypto-trading-bot/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/crypto/crypto-trading-bot/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.30
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

> talib@1.0.6 install /home/crypto/crypto-trading-bot/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

\
/home/crypto/crypto-trading-bot/node_modules/talib/src/lib/build.js:8
  let msbuildPath;
      ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/crypto/crypto-trading-bot/npm-debug.log
npm ERR! not ok code 0
`

Its fresh CentOs.

Thank you.

**Comment by Haehnchen** [comment]
talib and tulib always fails also on other bots. :)

On ubunto you need:
https://github.com/DeviaVir/zenbot#ubuntu-1604-step-by-step

maybe is this also possible for centos.
also think of provide a docker image at some points

**Comment by TopSecretShares** [comment]
Thank you. I am not lucky enough probably.

8080 port is listing bu cannot connect
```
bitmex@ubuntu:~$   curl localhost:8080
curl: (52) Empty reply from server
```

```
bitmex@ubuntu:~/crypto-trading-bot$ node index.js trade
body-parser deprecated undefined extended: provide extended option modules/http.js:47:25
**Webserver listening on: 0.0.0.0:8080**
(node:53521) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
{"message":"Mailer: {\"errno\":\"ENOTFOUND\",\"code\":\"ECONNECTION\",\"syscall\":\"getaddrinfo\",\"hostname\":\"mail.foo.de\",\"host\":\"mail.foo.de\",\"port\":465,\"command\":\"CONN\"}","level":"error","timestamp":"2019-01-08T05:04:08.972Z"}
(node:53521) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit
WebSocket [INFO]: Connected.
Bitmex: Connection opened.
{"op":"subscribe","args":"tradeBin1m:ADAH19"}
{"op":"subscribe","args":"tradeBin5m:ADAH19"}
{"op":"subscribe","args":"tradeBin1h:ADAH19"}
```

Does anybody else have the same issue?

**Comment by TopSecretShares** [comment]
Hi Dan, 

Can you please help me with it? I am pretty sure if you gent new VM you will get the same errors?
This bot looks so good to try.

Regards,
Vladi

**Comment by Haehnchen** [comment]
local issue; closing
