### ISSUE TITLE
Window - Can not install

### ISSUE THREAD

**Issue by mb-slo** [Haehnchen/crypto-trading-bot#184]
```
C:\Development\crypto-trading-bot\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\mitja.bombac\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\mitja.bombac\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure )

C:\Development\crypto-trading-bot\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\mitja.bombac\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "C:\Users\mitja.bombac\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  talib.cpp
  win_delay_load_hook.cc
c:\development\crypto-trading-bot\node_modules\talib\src\talib.cpp(85): warning C4996: 'Nan::Callback::Call': was decla
red deprecated [C:\Development\crypto-trading-bot\node_modules\talib\build\talib.vcxproj]
  c:\development\crypto-trading-bot\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\development\crypto-trading-bot\node_modules\talib\src\talib.cpp(95): warning C4996: 'Nan::Callback::Call': was decla
red deprecated [C:\Development\crypto-trading-bot\node_modules\talib\build\talib.vcxproj]
  c:\development\crypto-trading-bot\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\development\crypto-trading-bot\node_modules\talib\src\talib.cpp(546): warning C4996: 'Nan::Callback::Call': was decl
ared deprecated [C:\Development\crypto-trading-bot\node_modules\talib\build\talib.vcxproj]
  c:\development\crypto-trading-bot\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
LINK : fatal error LNK1104: cannot open file '..\src\lib\lib\ta_libc_csr.lib' [C:\Development\crypto-trading-bot\node_m
odules\talib\build\talib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mitja.bombac\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mitja.bombac\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Development\crypto-trading-bot\node_modules\talib
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.1.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mitja.bombac\AppData\Roaming\npm-cache\_logs\2021-01-02T20_05_08_812Z-debug.log

C:\Development\crypto-trading-bot>


I also install "https://www.npmjs.com/package/windows-build-tools"

Any idea?

```

**Comment by miguelangelramirez** [comment]
Try updating Node. 

Miguel A. Ramírez

**Comment by mb-slo** [comment]
Same with "v14.15.3"

**Comment by Wladastic** [comment]
run in docker

**Comment by mrseeker** [comment]
My guess is that talib does not work under Windows... Can you manually install that dependency?
