### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by qvs5010** [Haehnchen/crypto-trading-bot#185]
Hi 

I get the following error when i try to start the bot.

is there something i have to do? i added my api details.

```
[root@crypto-trading-bot-master]# npm start

> crypto-trading-bot@0.0.0 start /var/tradeBot/crypto-trading-bot-master
> node index.js trade

internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /var/tradeBot/crypto-trading-bot-master/node_modules/talib/build/Release/talib.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/tradeBot/crypto-trading-bot-master/src/utils/indicators.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-03T15_50_37_645Z-debug.log

```

**Comment by qvs5010** [comment]
Fixed, just had to reinstall "npm i talib"

**Comment by sankhaKarunasekara** [comment]
`npm i talib` not worked for me.
