### ISSUE TITLE
Can't Start Windows

### ISSUE THREAD

**Issue by tarikaydin16** [Haehnchen/crypto-trading-bot#196]
```

D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master>npm start

> crypto-trading-bot@0.0.0 start D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master
> node index.js trade

internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\lib\binding\Release\node-v72-win32-x64\tulind.node'
Require stack:
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\index.js
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\src\utils\technical_analysis.js
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\src\modules\ta.js
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\src\modules\services.js
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\src\command\trade.js
- D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\dizi\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\node_modules\\tulind\\index.js',
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\src\\utils\\technical_analysis.js',
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\src\\modules\\ta.js',
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\src\\modules\\services.js',
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\src\\command\\trade.js',
    'D:\\dizi\\crypto-trading-bot-master\\crypto-trading-bot-master\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tarik\AppData\Roaming\npm-cache\_logs\2021-01-18T20_22_12_518Z-debug.log


```

**Comment by mrseeker** [comment]
As the error says: "Module not found", and checking which module, its tulind...
