### ISSUE TITLE
Error at install (Windows 8.1)

### ISSUE THREAD

**Issue by PajaCool** [Haehnchen/crypto-trading-bot#207]
Hi,

I am completely new to nodejs and i can't figure out, how to finish installation of this package. After downloading and installing nodejs 7.3 (as suggested by the package.json), I try to run install --production command and get this error.

What am I missing? Thank you for any help.

Paja

`c:\Users\User\Downloads\crypto-trading-bot-master>npm install --production
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type functi
on
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\no
de_modules\@npmcli\move-file\index.js:26:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\no
de_modules\cacache\lib\util\move-file.js:8:14)
C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\config\l
ib\index.js:163
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modul
es\@npmcli\config\lib\index.js:163:13)
    at process.errorHandler (C:\Users\User\AppData\Roaming\npm\node_modules\npm\
lib\utils\error-handler.js:171:32)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:332:26)`

**Comment by loic-roux-404** [comment]
Use a better node version and update your computer or work on a linux machine.
