### ISSUE TITLE
Backtest candle issue

### ISSUE THREAD

**Issue by exca11** [Haehnchen/crypto-trading-bot#213]
Hello,
First , many thanks for your work.

When backtesting with only trader and noop strategy causes an error below docker logs.
Any advice?

Thank you.

(node:20) UnhandledPromiseRejectionWarning: Error: Call to undefined indicator: {"indicator":"candles","key":"foreign_candle","period":"15m","source":"close","options":{"exchange":"binance","symbol":"BTCUSDT"}}

at indicators.map.filter.filter.map.indicator (/usr/src/app/src/utils/technical_analysis.js:102:15)

at Array.map (<anonymous>)

at Object.calculateReadyIndicators (/usr/src/app/src/utils/technical_analysis.js:89:8)

at Object.createIndicatorsLookback (/usr/src/app/src/utils/technical_analysis.js:119:45)

at StrategyManager.getTaResult (/usr/src/app/src/modules/strategy/strategy_manager.js:262:33)

at process._tickCallback (internal/process/next_tick.js:68:7)

(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ramumanavalan** [comment]
For me also same issue for candles indicator when I'm using pivot_reversal_strategy

`(node:50427) UnhandledPromiseRejectionWarning: Error: Call to undefined indicator: {"indicator":"candles","key":"candles_1m","period":"1m","source":"close","options":{}}
    at indicators.map.filter.filter.map.indicator (/var/app/project/bncbot/src/utils/technical_analysis.js:102:15)
     at Array.map (<anonymous>)
     at Object.calculateReadyIndicators (/var/app/project/bncbot/src/utils/technical_analysis.js:89:8)
    at Object.createIndicatorsLookback (/var/app/project/bncbot/src/utils/technical_analysis.js:119:45)
    at StrategyManager.getTaResult (/var/app/project/bncbot/src/modules/strategy/strategy_manager.js:240:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:50427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Inside `src/utils/indicator.js` there is no sourceCandles named like above `candles`
`sourceCandle: ['cci', 'pivot_points_high_low', 'obv', 'ao', 'mfi', 'stoch', 'vwma', 'atr', 'adx', 'volume_profile', 'volume_by_price', 'ichimoku_cloud', 'zigzag', 'wicked', 'heikin_ashi', 'psar', 'hma']`

Anyone please help us to solve this issue??

**Comment by anakein** [comment]
add this function into indicators.js

 candles: function(source, indicator) {
    return new Promise(resolve => {

      const input = {
        close: [],
        high: [],
        low: [],
        open: [],
        timestamp: [],
        volume: []
      };

      source.forEach(candle => {
        input.close.push(candle.close);
        input.high.push(candle.high);
        input.low.push(candle.low);
        input.open.push(candle.open);
        input.timestamp.push(candle.time);
        input.volume.push(candle.volume);
      });

      resolve({ [indicator.key]: input });
    });
  },

**Comment by bird59** [comment]
thank you for this code but i am this error :

`candles1m.slice is not a function`

**Comment by anakein** [comment]
> candles1m

into noob.js i cant to see candles1m.slice
what strategy are you using?

**Comment by bird59** [comment]
I use traders ans pivot_reversal_strategie. I have the same error with strategies
