### ISSUE TITLE
Unable to start - SqliteError: no such table: candlesticks

### ISSUE THREAD

**Issue by xxxjajoxxx** [Haehnchen/crypto-trading-bot#215]
`
(node:20) UnhandledPromiseRejectionWarning: SqliteError: no such table: candlesticks
    
    at resolve (/usr/src/app/src/modules/repository/candlestick_repository.js:93:30)
    at new Promise (<anonymous>)
    at CandlestickRepository.insertCandles (/usr/src/app/src/modules/repository/candlestick_repository.js:92:12)
    at CandleImporter.insertCandles (/usr/src/app/src/modules/system/candle_importer.js:31:39)
    at Timeout.CandleImporter.setInterval [as _onTimeout] (/usr/src/app/src/modules/system/candle_importer.js:20:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)`

**Comment by ArnisL** [comment]
Did you initialize the database?

Try running:

```
$ sqlite3 bot.db < bot.sql
```

**Comment by xxxjajoxxx** [comment]
now I done it and thi is respone
`Error: near line 3: attempt to write a readonly database
Error: near line 16: no such table: main.candlesticks
Error: near line 19: no such table: main.candlesticks
Error: near line 20: no such table: main.candlesticks
Error: near line 22: attempt to write a readonly database
Error: near line 36: no such table: main.candlesticks_log
Error: near line 38: attempt to write a readonly database
Error: near line 47: no such table: main.ticker
Error: near line 50: attempt to write a readonly database
Error: near line 58: no such table: main.ticker_log
Error: near line 59: no such table: main.ticker_log
Error: near line 61: attempt to write a readonly database
Error: near line 73: no such table: main.signals
Error: near line 75: attempt to write a readonly database
Error: near line 82: no such table: main.logs
Error: near line 83: no such table: main.logs
Error: near line 84: no such table: main.logs`
