### ISSUE TITLE
IS IT POSSIBLE TO RUN THIS BOT IN WINDOWS 10?

### ISSUE THREAD

**Issue by jsut21** [Haehnchen/crypto-trading-bot#274]
Can you tell me how to use it in more detail?

ACTUALLY, I TRIED TO RUN THIS BUT...

926 warn eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
927 warn eslint-config-esnext@4.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
928 warn eslint-config-node@4.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
929 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
930 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
931 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
931 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
931 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
931 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
932 verbose stack Error: talib@1.1.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
932 verbose stack Exit status 1
932 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
932 verbose stack     at EventEmitter.emit (events.js:198:13)
932 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
932 verbose stack     at ChildProcess.emit (events.js:198:13)
932 verbose stack     at maybeClose (internal/child_process.js:982:16)
932 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
933 verbose pkgid talib@1.1.3
934 verbose cwd C:\Users\Lis\Desktop\crypto-trading-bot
935 verbose Windows_NT 10.0.19043
936 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3"
937 verbose node v10.24.1
938 verbose npm  v6.14.12
939 error code ELIFECYCLE
940 error errno 1
941 error talib@1.1.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
941 error Exit status 1
942 error Failed at the talib@1.1.3 install script.
942 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jsut21** [comment]
I REALLY WANT TO TRY THIS.

PLEASE HELP ME

**Comment by Wladastic** [comment]
Please use wsl then.
Node on windows is a pain

**Comment by jsut21** [comment]
IT WORKS
THANK YOU.
