### ISSUE TITLE
Cannot find Winston-telegram?

### ISSUE THREAD

**Issue by Wladastic** [Haehnchen/crypto-trading-bot#283]
For some reason docker-compose cannot start anymore.
The folder is there, I tried adding chmod 777 -R onto it, no difference.

`
crypto-trading-bot | > crypto-trading-bot@0.0.0 start /usr/src/app
crypto-trading-bot | > node index.js trade
crypto-trading-bot |
crypto-trading-bot | internal/modules/cjs/loader.js:638
crypto-trading-bot |     throw err;
crypto-trading-bot |     ^
crypto-trading-bot |
crypto-trading-bot | Error: Cannot find module 'winston-telegram'
crypto-trading-bot |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
crypto-trading-bot |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
crypto-trading-bot |     at Module.require (internal/modules/cjs/loader.js:692:17)
crypto-trading-bot |     at require (internal/modules/cjs/helpers.js:25:18)
crypto-trading-bot |     at Object.<anonymous> (/usr/src/app/src/modules/services.js:46:31)
crypto-trading-bot |     at Module._compile (internal/modules/cjs/loader.js:778:30)
crypto-trading-bot |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
crypto-trading-bot |     at Module.load (internal/modules/cjs/loader.js:653:32)
crypto-trading-bot |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
crypto-trading-bot |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
crypto-trading-bot | npm ERR! code ELIFECYCLE
crypto-trading-bot | npm ERR! errno 1
crypto-trading-bot | npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
crypto-trading-bot | npm ERR! Exit status 1
crypto-trading-bot | npm ERR!
crypto-trading-bot | npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
crypto-trading-bot | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
crypto-trading-bot |
crypto-trading-bot | npm ERR! A complete log of this run can be found in:
crypto-trading-bot | npm ERR!     /root/.npm/_logs/2021-12-29T15_05_51_814Z-debug.log`

**Comment by Wladastic** [comment]
the problem only appears with docker,
I started the bot using screen and "npm run start"
