### ISSUE TITLE
Getting windows docker issue SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by cinderspire** [Haehnchen/crypto-trading-bot#305]
SyntaxError: Unexpected token ?

    at Module._compile (internal/modules/cjs/loader.js:723:23)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

    at Module.load (internal/modules/cjs/loader.js:653:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

    at Module.require (internal/modules/cjs/loader.js:692:17)

    at require (internal/modules/cjs/helpers.js:25:18)

    at Object.<anonymous> (/usr/src/app/src/modules/services.js:46:31)

    at Module._compile (internal/modules/cjs/loader.js:778:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by cinderspire** [comment]
Just dont change name xd

**Comment by cinderspire** [comment]
Just dont change name xd
