### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by xinmans** [Haehnchen/crypto-trading-bot#325]
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-08T14_23_20_881Z-debug.log
> crypto-trading-bot@0.0.0 start /usr/src/app
> node index.js trade
/usr/src/app/node_modules/winston-telegram/lib/winston-telegram.js:46
    this.handleExceptions = options.handleExceptions ?? true
                                                      ^
SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/modules/services.js:46:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
npm ERR! Exit status 1

 
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-08T14_25_57_582Z-debug.log

**Comment by mawenchao** [comment]
me too

**Comment by FredMichel** [comment]
Same for me.

**Comment by spikkie** [comment]
I also see this
