### ISSUE TITLE
Websocket Error 

### ISSUE THREAD

**Issue by zakirattari26** [Haehnchen/crypto-trading-bot#340]
Websocket Error 

Webserver listening on: http://0.0.0.0:8080                   node:events:491                                                     throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/root/bot/crypto-trading-bot/node_modules/ws/lib/websocket.js:285:14)
    at ReconnectingWebSocket._disconnect (/root/bot/crypto-trading-bot/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)                                         at ReconnectingWebSocket._handleError (/root/bot/crypto-trading-bot/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/root/bot/crypto-trading-bot/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
    at Timeout.<anonymous> (/root/bot/crypto-trading-bot/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
    at listOnTimeout (node:internal/timers:559:17)                at processTimers (node:internal/timers:502:7)             Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/root/bot/crypto-trading-bot/node_modules/ws/lib/websocket.js:1002:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)                 at processTimers (node:internal/timers:502:7)

**Comment by johnsmith0305** [comment]
Hello! How are you? I specialize in Express.js development and have skills in Trading Bot development. I'm interested in joining your team to help solve issues.

**Comment by chenxidev1129** [comment]
me too. Who can I join into this project?
