### ISSUE TITLE
TypeError: PQueue is not a constructor

### ISSUE THREAD

**Issue by POCO10** [Haehnchen/crypto-trading-bot#63]
Hey there,
with the newest commits I am getting the following error when starting the bot after the first tick arrives. The error repeats with every new tick:

`(node:2141) UnhandledPromiseRejectionWarning: TypeError: PQueue is not a constructor
    at TickListener.onTick (/Users/XXX/bot/modules/listener/tick_listener.js:123:23)
    at EventEmitter.eventEmitter.on (/Users/XXX/bot/modules/trade.js:123:29)
    at EventEmitter.emit (events.js:182:13)
    at Timeout.setInterval [as _onTimeout] (/Users/XXX/bot/modules/trade.js:80:30)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
(node:2141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
`

Any idea what change could cause this?

**Comment by POCO10** [comment]
Sorry! Made a mistake by updating all node packages. After downgrading them to the original version its working again!
