### ISSUE TITLE
Cannot find module node_modules/tulind/lib/binding/Release/node-v57-linux-x64/tulind.node

### ISSUE THREAD

**Issue by kastjan1989** [Haehnchen/crypto-trading-bot#70]
Hi guys, trying to run index.js

sudo node index.js trade
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/***/Downloads/bitmex_orig/crypto-trading-bot/node_modules/tulind/lib/binding/Release/node-v57-linux-x64/tulind.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/***/Downloads/bitmex_orig/crypto-trading-bot/node_modules/tulind/index.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

ideas how to fix it?

**Comment by kastjan1989** [comment]
sudo npm install tulind
npm WARN @tensorflow/tfjs-data@0.2.3 requires a peer of @tensorflow/tfjs-core@0.15.4 but none was installed.

**Comment by kastjan1989** [comment]
****@******:~/Downloads/bitmex_orig/crypto-trading-bot$ ls node_modules/tulind/
appveyor.yml  AUTHORS  binding.gyp  example.js  external  index.js  LICENSE  node_modules  npm-debug.log  package.json  Readme.md  test.js  tulind.cpp  tulipnode

**Comment by mrseeker** [comment]
Did you install npm as user or root? Looks like npm did not install the node library required...

**Comment by deeppaz** [comment]
go to node modules folder then find tulind folder, open terminal as  tulind. finally write command this "npm install"

**Comment by Haehnchen** [comment]
not related to thos project maybe; use the docker enviroment
