### ISSUE TITLE
Cannot find module - ../dict/signal_results.js

### ISSUE THREAD

**Issue by wayjeeair** [Haehnchen/crypto-trading-bot#71]
Never had this issue until I added new strategies into the strategy folder. Removed the strategies, and yet the issue remains. 

(node:78151) UnhandledPromiseRejectionWarning: Error: Cannot find module 'Users/user/Downloads/crypto-trading-bot-master/modules/strategy/dict/signal_results.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/user/Downloads/crypto-trading-bot-master/modules/strategy/strategies/cci.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:78151) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 866)

**Comment by mrseeker** [comment]
Name should be ../dict/signal_result.js, are you on the latest release?

**Comment by egisz** [comment]
If you copied some sample strategy from it's default location crypto-trading-bot/modules/strategy/strategies/... to custom strategies location crypto-trading-bot/var/strategies/_some_new_strategy.js_, then you have to update your new strategy include path as it points to wrong location: 

`let SignalResult = require('../../modules/strategy/dict/signal_result')`

**Comment by Haehnchen** [comment]
path issue; possible solution given
