### ISSUE TITLE
Before posting an issue. Please use the docker to run this. 

### ISSUE THREAD

**Issue by hatzkel** [Haehnchen/crypto-trading-bot#78]
Run docker and follow the instructions in the readme. 

All problems solved.

If you can't get this running. It is far beyond your expertise and you will never get it running because you have too much to learn before you can even begin to work it. Move on.

**Comment by DominiqueGEORGES** [comment]
Hi,

I can't build a docker image on my Mac Book Pro M1 MAx.

➜  crypto-trading-bot git:(master) docker-compose build
[+] Building 0.1s (12/12) FINISHED                                                                                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                         0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                            0.0s
 => => transferring context: 34B                                                                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:10                                                                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                            0.0s
 => => transferring context: 18.01kB                                                                                                                                                                                                                         0.0s
 => [1/7] FROM docker.io/library/node:10                                                                                                                                                                                                                     0.0s
 => CACHED [2/7] RUN apt-get update && apt-get install -y     sqlite && rm -rf /var/lib/apt/lists/*                                                                                                                                                          0.0s
 => CACHED [3/7] WORKDIR /usr/src/app                                                                                                                                                                                                                        0.0s
 => CACHED [4/7] COPY package.json /usr/src/app/                                                                                                                                                                                                             0.0s
 => CACHED [5/7] RUN npm install --production &&     npm cache clean --force                                                                                                                                                                                 0.0s
 => CACHED [6/7] COPY . /usr/src/app                                                                                                                                                                                                                         0.0s
 => CACHED [7/7] RUN npm run postinstall                                                                                                                                                                                                                     0.0s
 => exporting to image                                                                                                                                                                                                                                       0.0s
 => => exporting layers                                                                                                                                                                                                                                      0.0s
 => => writing image sha256:521aceca78d4534d140fe83ae8173d5e955144d7aa8f3d3f937acea589cb6549                                                                                                                                                                 0.0s
 => => naming to docker.io/library/node:10                                                                                                                                                                                                                   0.0s
➜  crypto-trading-bot git:(master)

**Comment by DominiqueGEORGES** [comment]
running the Docker container fails.


➜  crypto-trading-bot git:(master) docker-compose up
[+] Running 1/1
 ⠿ Container crypto-trading-bot  Recreated                                                                                                                                                                                                                   0.1s
Attaching to crypto-trading-bot
crypto-trading-bot  | 
crypto-trading-bot  | > crypto-trading-bot@0.0.0 start /usr/src/app
crypto-trading-bot  | > node index.js trade
crypto-trading-bot  | 
crypto-trading-bot  | /usr/src/app/node_modules/winston-telegram/lib/winston-telegram.js:46
crypto-trading-bot  |     this.handleExceptions = options.handleExceptions ?? true
crypto-trading-bot  |                                                       ^
crypto-trading-bot  | 
crypto-trading-bot  | SyntaxError: Unexpected token ?
crypto-trading-bot  |     at Module._compile (internal/modules/cjs/loader.js:723:23)
crypto-trading-bot  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
crypto-trading-bot  |     at Module.load (internal/modules/cjs/loader.js:653:32)
crypto-trading-bot  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
crypto-trading-bot  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
crypto-trading-bot  |     at Module.require (internal/modules/cjs/loader.js:692:17)
crypto-trading-bot  |     at require (internal/modules/cjs/helpers.js:25:18)
crypto-trading-bot  |     at Object.<anonymous> (/usr/src/app/src/modules/services.js:46:31)
crypto-trading-bot  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
crypto-trading-bot  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
crypto-trading-bot  | npm ERR! code ELIFECYCLE
crypto-trading-bot  | npm ERR! errno 1
crypto-trading-bot  | npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
crypto-trading-bot  | npm ERR! Exit status 1
crypto-trading-bot  | npm ERR! 
crypto-trading-bot  | npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
crypto-trading-bot  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
crypto-trading-bot  | 
crypto-trading-bot  | npm ERR! A complete log of this run can be found in:
crypto-trading-bot  | npm ERR!     /root/.npm/_logs/2022-08-08T15_50_17_274Z-debug.log
crypto-trading-bot exited with code 1
➜  crypto-trading-bot git:(master)
