### ISSUE TITLE
Error: Cannot find module 'ccxt'

### ISSUE THREAD

**Issue by hatzkel** [Haehnchen/crypto-trading-bot#90]
After pulling the newest commit and spinning up the docker this occurs.

```
> crypto-trading-bot@0.0.0 start /usr/src/app
> node index.js trade

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ccxt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/exchange/ftx.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/modules/services.js:58:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/command/trade.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-trading-bot@0.0.0 start: `node index.js trade`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crypto-trading-bot@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-15T01_49_53_294Z-debug.log
```

**Comment by hatzkel** [comment]
After npm install ccxt from within the container just to see if it would resolve it:

```

(node:18) UnhandledPromiseRejectionWarning: SqliteError: database disk image is malformed
    at exchangeCandlesticks.forEach.exchangeCandlestick (/usr/src/app/modules/repository/candlestick_repository.js:74:28)
    at Array.forEach (<anonymous>)
    at db.transaction (/usr/src/app/modules/repository/candlestick_repository.js:61:38)
    at sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at resolve (/usr/src/app/modules/repository/candlestick_repository.js:76:15)
    at new Promise (<anonymous>)
    at CandlestickRepository.insertCandles (/usr/src/app/modules/repository/candlestick_repository.js:54:16)
    at CandleImporter.insertCandles (/usr/src/app/modules/system/candle_importer.js:34:43)
    at Timeout.CandleImporter.setInterval [as _onTimeout] (/usr/src/app/modules/system/candle_importer.js:22:32)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18) UnhandledPromiseRejectionWarning: SqliteError: database disk image is malformed
    at exchangeCandlesticks.forEach.exchangeCandlestick (/usr/src/app/modules/repository/candlestick_repository.js:74:28)
    at Array.forEach (<anonymous>)
    at db.transaction (/usr/src/app/modules/repository/candlestick_repository.js:61:38)
    at sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at resolve (/usr/src/app/modules/repository/candlestick_repository.js:76:15)
    at new Promise (<anonymous>)
    at CandlestickRepository.insertCandles (/usr/src/app/modules/repository/candlestick_repository.js:54:16)
    at CandleImporter.insertCandles (/usr/src/app/modules/system/candle_importer.js:34:43)
    at Timeout.CandleImporter.setInterval [as _onTimeout] (/usr/src/app/modules/system/candle_importer.js:22:32)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:18) UnhandledPromiseRejectionWarning: SqliteError: database disk image is malformed
    at exchangeCandlesticks.forEach.exchangeCandlestick (/usr/src/app/modules/repository/candlestick_repository.js:74:28)
    at Array.forEach (<anonymous>)
    at db.transaction (/usr/src/app/modules/repository/candlestick_repository.js:61:38)
    at sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at resolve (/usr/src/app/modules/repository/candlestick_repository.js:76:15)
    at new Promise (<anonymous>)
    at CandlestickRepository.insertCandles (/usr/src/app/modules/repository/candlestick_repository.js:54:16)
    at CandleImporter.insertCandles (/usr/src/app/modules/system/candle_importer.js:34:43)
    at Timeout.CandleImporter.setInterval [as _onTimeout] (/usr/src/app/modules/system/candle_importer.js:22:32)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:18) UnhandledPromiseRejectionWarning: SqliteError: database disk image is malformed
    at exchangeCandlesticks.forEach.exchangeCandlestick (/usr/src/app/modules/repository/candlestick_repository.js:74:28)
    at Array.forEach (<anonymous>)
    at db.transaction (/usr/src/app/modules/repository/candlestick_repository.js:61:38)
    at sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at resolve (/usr/src/app/modules/repository/candlestick_repository.js:76:15)
    at new Promise (<anonymous>)
    at CandlestickRepository.insertCandles (/usr/src/app/modules/repository/candlestick_repository.js:54:16)
    at CandleImporter.insertCandles (/usr/src/app/modules/system/candle_importer.js:34:43)
    at Timeout.CandleImporter.setInterval [as _onTimeout] (/usr/src/app/modules/system/candle_importer.js:22:32)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by minhphuc429** [comment]
run command `docker-compose build` rebuild new docker image again
