### ISSUE TITLE
node index.js trade Fail (MODULE_NOT_FOUND)

### ISSUE THREAD

**Issue by emin-karadag** [Haehnchen/crypto-trading-bot#98]
Hello,
When I type and run "node index.js trade" I get the following error.
Can you help me?

`internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\lib\binding\Release\node-v72-win32-x64\tulind.node'
Require stack:
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\index.js
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\utils\technical_analysis.js
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\modules\listener\create_order_listener.js
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\modules\services.js
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\command\trade.js
- C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\memet\Downloads\crypto-trading-bot-master\crypto-trading-bot-master\node_modules\tulind\index.js:4:14)  
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\node_modules\\tulind\\index.js',
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\utils\\technical_analysis.js',
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\modules\\listener\\create_order_listener.js',       
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\modules\\services.js',
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\command\\trade.js',
    'C:\\Users\\memet\\Downloads\\crypto-trading-bot-master\\crypto-trading-bot-master\\index.js'
  ]
}`

![hata](https://user-images.githubusercontent.com/7556164/71868275-864a0800-311e-11ea-9e7e-280e2f2c6593.PNG)

**Comment by Haehnchen** [comment]
yes, docker will help. plain windows is alway tricky. wsl may also help
